service: vuttrapi

provider:
  name: aws
  runtime: nodejs12.x
  stage : dev
  region : us-east-1
  # [sugestão] Separar o arquivo de variáveis de ambiente
  environment:
    TOOL_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

# [sugestão] Utilizar mais os "plugins" do framework, como por exemplo:
# serverless-plugin-typescript é um plug-in para suporte ao Typecript
# serverless-dynamodb-local é um plug-in para permitir o desenvolvimento offline
# serverless-offline é um plug-in para permitir o desenvolvimento offline
# serverless-prune-plugin permite a remoção de todas as versões, exceto as mais recentes, de funções gerenciadas da AWS
# serverless-plugin-tracing habilita o AWS X-Ray (https://aws.amazon.com/xray/) para toda a Serverless stack ou lambdas individuais.

# [melhoria] configurar o CORS no serverless.yml (aqui) e nas funções utilizando o middleware `cors()` 
functions:
  # [melhoria] Console Warning:
  # Serverless: Warning! You're using the AWS_PROXY in combination with a request configuration in your function 
  # "getAllTools". Only the request.parameters, request.schema configs are available in conjunction with AWS_PROXY. Serverless will remove this configuration automatically before deployment.
  getAllTools:
    handler: domain/tools.getAll
    memorySize: 256
    description: Return all the very useful tools to remind that attend the tag filter if informed.
    events:
      - http: 
          path: tools
          method: get
          # authorizer:
          #   type: COGNITO_USER_POOLS
          #   authorizerId:
          #     Ref: ApiGatewayAuthorizer
          request:
                template:
                  application/json: >
                    {
                      "tag" : "$input.params('tag')",
                    }
  insertTool:
    handler: domain/tools.insert
    memorySize: 256
    description: Insert a new very useful tool to remind.
    events:
      - http: 
          path: tools
          method: post
          # cors: true
          # authorizer:
          #   type: COGNITO_USER_POOLS
          #   authorizerId:
          #     Ref: ApiGatewayAuthorizer
  removeTool:
    handler: domain/tools.remove
    memorySize: 256
    description: Remove a very useful tool to remind by its id.
    events:
      - http: 
          path: tools/{id}
          method: delete
          # authorizer:
          #   type: COGNITO_USER_POOLS
          #   authorizerId:
          #     Ref: ApiGatewayAuthorizer
          request:
            parameters:
              paths:
                id: true
resources:
  Resources:
    ToolsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.TOOL_TABLE}
    CognitoUserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        MfaConfiguration: OFF
        UserPoolName: my-user-pool
        UsernameAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: False
            RequireNumbers: True
            RequireSymbols: False
            RequireUppercase: True
    CognitoUserPoolClient:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
        ClientName: my-user-pool-client
        GenerateSecret: False
        UserPoolId:
          Ref: CognitoUserPool
    ApiGatewayAuthorizer:
      DependsOn:
        - ApiGatewayRestApi
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: cognito-authorizer
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - Fn::GetAtt: [CognitoUserPool, Arn]